spring: #띄어쓰기 없음
#  datasource: #띄어쓰기 2칸
#    url: jdbc:h2:tcp://localhost/~/IdeaProjects/springtoy #4칸
#    username: sa
#    password:
#    driver-class-name: org.h2.Driver
  datasource:
    url: jdbc:mysql://192.168.55.215:3306/springtoy?characterEncoding=UTF-8
    username: root # mariadb의 기본 사용자 이름입니다. 환경에 따라 변경하실 수 있습니다.
    password: root    # mariadb의 비밀번호를 설정하셨다면 여기에 입력하세요.
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: localhost
    port: 6379
  mail:
    host: smtp.gmail.com
    port: 587
    username: hdbstn3055@gmail.com
    password: 
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
    auth-code-expiration-millis: 1800000  # 30 * 60 * 1000 == 30분

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        # show_sql: true
        format_sql: true
        default_batch_fetch_size: 100
    open-in-view: false

logging.level: #띄어쓰기 없음
  org.hibernate.SQL: debug #띄어쓰기 2칸
  org.hibernate.type: trace #띄어쓰기 2칸

jwt:
  secret-key: a2FyaW10b2thcmltdG9rYXJpbXRva2FyaW10b2thcmltdG9rYXJpbXRva2FyaW10b2thcmltdG9rYXJpbXRva2FyaW10b2thcmltdG9rYXJpbXRva2FyaW10b2thcmltdG9rYXJpbXRva2FyaW10b2thcmltdG9rYXJpbXRva2FyaW10b2thcmltdG9rYXJpbQ==
  accessToken-validity-in-seconds: 1800
  refreshToken-validity-in-seconds: 3600

aes:
  secret-key: CDEFGHIJKLMNOPQRSTUVWX0123456789
