spring: #띄어쓰기 없음
  datasource: #띄어쓰기 2칸
    url: jdbc:h2:tcp://localhost/~/IdeaProjects/springtoy #4칸
    username: sa
    password:
    driver-class-name: org.h2.Driver
  redis:
    host: localhost
    port: 6379
  mail:
    host: smtp.gmail.com
    port: 587
    username: hdbstn3055@gmail.com
    password: 
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
    auth-code-expiration-millis: 1800000  # 30 * 60 * 1000 == 30분



  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        # show_sql: true
        format_sql: true
        default_batch_fetch_size: 100
    open-in-view: false

logging.level: #띄어쓰기 없음
  org.hibernate.SQL: debug #띄어쓰기 2칸
  org.hibernate.type: trace #띄어쓰기 2칸

jwt:
  secret-key: a2FyaW10b2thcmltdG9rYXJpbXRva2FyaW10b2thcmltdG9rYXJpbXRva2FyaW10b2thcmltdG9rYXJpbXRva2FyaW10b2thcmltdG9rYXJpbXRva2FyaW10b2thcmltdG9rYXJpbXRva2FyaW10b2thcmltdG9rYXJpbXRva2FyaW10b2thcmltdG9rYXJpbQ==
  accessToken-validity-in-seconds: 1800
  refreshToken-validity-in-seconds: 3600

aes:
  secret-key: CDEFGHIJKLMNOPQRSTUVWX0123456789

cloud:
  aws:
    s3:
      bucket: 
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false
    key:
      access-key: 
      secret-key: 
